### ISSUE TITLE
6.2.4 Client

### ISSUE THREAD

**Issue by Crandalius** [nathalis/NCX-WOD-Trinity#1]
Hi there, 

I saw you managed to fix the compiles on the 6.2.4 source.

Would you by any chance have the 6.2.4 client that you can upload? 

Thanks

**Comment by nathalis** [comment]
Client: 6.2.4.21742
Total size: 28.57 GB
link: https://mega.nz/folder/nZ5TFQyT#Lp7MRsGtnPtltprS7jAnhg

**Comment by Crandalius** [comment]
Amazing, you're the man!

**Comment by Crandalius** [comment]
@nathalis 

Thanks again for the client, I'm only having issues with compiling the core. Can I compile this source on VS2017? I'm trying 2013 now.

Alternatively. Would it be possible if you can upload a compiled core of the source, I'd just like to test the client and see how it works ingame. 

Thanks for all your help and interest

**Comment by nathalis** [comment]
try complete repack:
https://aquayoup.123.fr/thread-2.html

for Win. server binaries:
https://z.aquayoup.123.fr/6x/Core-serveur-_2019-05-05.rar

**Comment by Crandalius** [comment]
Thank you again, I will follow the community from there.

**Comment by Crandalius** [comment]
@nathalis 

Thank you for the below,

I've copied your latest patch files you uploaded and keep getting the below

Program:	D:\Games\6.2.4.21742\Wow_Patched.exe
ProcessID:	13288

Unable to read data for DBFilesClient\Startup_Strings.dbc [Key 908e3f676e078ebc75050ad3cbc4d464]: E_NOT_AVAILABLE

> Client: 6.2.4.21742
> Total size: 28.57 GB
> link: https://mega.nz/folder/nZ5TFQyT#Lp7MRsGtnPtltprS7jAnhg

Any suggestions that you might have?

**Comment by nathalis** [comment]
try these files: https://drive.google.com/open?id=1bZQGAohehpi3FNr5LDj9tf8FRnpXRdmj

**Comment by Crandalius** [comment]
I just tried them, I get the downloading dialog but it keeps on attempting to download after using the start.bat that was within those files. I suppose yours is working fine cause I saw your WTF config had a local IP in there.

Do you have discord by any chance?

**Comment by nathalis** [comment]
nathalis#4137

**Comment by nathalis** [comment]
By the way, why do not try Legion Server?

**Comment by Crandalius** [comment]
@nathalis 

I've added you on Discord. I'm not to fond of legion. Have you managed to get the uwow core to work?
